openapi: 3.2.0
info:
  title: Termius API Bridge Group API
  description: '# Welcome

    You are viewing the REST API documentation for the Termius API Bridge.'
  termsOfService: https://termius.com/terms-of-use
  contact:
    email: support@termius.com
  license:
    name: Proprietary and confidential
  version: 0.0.1
tags:
- name: Group
  description: Create a new Group
paths:
  /v1/group/{external_id}/:
    post:
      tags:
      - Group
      operationId: createGroup
      summary: Create a new Group in the vault
      description: 'Pass a vault name in the `vault` field and the group `label`.


        Example of the request that creates a new group in `Team` vault with

        `external_id` as `client-123`, label `John Doe`,

        ssh port `22`, and ssh credentials in `username` and `password`

        properties, and SSH key in the `key` property:


        - path: `/v1/group/client-123/`

        - body:

        ```

        {

        "vault": "Team",

        "label": "John Doe",

        "ssh": {

        "port": 22,

        "credentials": {

        "username": "username",

        "password": "password",

        "key": {

        "label": "shared with the team",

        "private": "-----BEGIN OPENSSH PRIVATE KEY-----\nb3Blbn..."

        }

        }

        }

        }

        ```


        Optionally, pass the parent group `external_id` in the `group` field

        instead of the `vault`.

        Create a parent group via this API before creating a nested group.'
      parameters:
      - $ref: '#/components/parameters/GroupExternalID'
      requestBody:
        $ref: '#/components/requestBodies/Group'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateGroupResponse'
        '400':
          description: Failed request. Check the request body.
components:
  schemas:
    Port:
      type: integer
      format: int64
      default: 22
      minimum: 1
      maximum: 65535
    Group:
      type: object
      required:
      - label
      allOf:
      - $ref: '#/components/schemas/GroupReference'
      - $ref: '#/components/schemas/VaultReference'
      example:
        vault: Team
        label: Client John Doe
      properties:
        label:
          type: string
          example: Client John Doe
        ssh:
          type: object
          properties:
            port:
              $ref: '#/components/schemas/Port'
            credentials:
              allOf:
              - $ref: '#/components/schemas/Credentials'
              properties:
                key:
                  $ref: '#/components/schemas/SShKey'
        telnet:
          type: object
          properties:
            port:
              $ref: '#/components/schemas/Port'
            credentials:
              $ref: '#/components/schemas/Credentials'
    Credentials:
      properties:
        username:
          type: string
        password:
          type: string
    GroupReference:
      type: object
      required:
      - group
      properties:
        group:
          type: string
          example: client-1234
    CreateGroupResponse:
      type: object
    SShKey:
      required:
      - label
      - private
      properties:
        label:
          type: string
        private:
          type: string
        public:
          type: string
    VaultReference:
      type: object
      required:
      - vault
      properties:
        vault:
          type: string
          example: Team
  requestBodies:
    Group:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Group'
  parameters:
    GroupExternalID:
      name: external_id
      in: path
      description: Group ID in your original system, e.g., a client id.
      required: true
      example: client-1234
      schema:
        type: string
externalDocs:
  description: Termius Documentation
  url: https://support.termius.com/hc/en-us/
